{% set name = "pandas-dev-flaker" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas_dev_flaker-{{ version }}.tar.gz
  sha256: 3e81a13693ada41d6f095598bc75c41f28e93043a495f2b6183f9847dc910aeb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flake8 >=3.8
    # Only required for python<3.8 but always include for noarch: python
    - importlib-metadata
    - python >=3.6

test:
  imports:
    - pandas_dev_flaker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pandas-dev/pandas-dev-flaker
  summary: Linter for contributing to pandas
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
